/**
 * Recommended menu keys for each portal — strings MUST match backend `SYSTEM_MENUS.name`
 * (`zanezion-backend/zanzoin-backend/config/systemMenus.js`) when saving `menu_permissions.menu_name`.
 *
 * UI labels in Sidebar can differ; DB rows always use these names.
 */
export const RECOMMENDED_MENU_NAMES_BY_PORTAL = {
  /** DB role: admin — company / institutional admin (what you add from Super Admin) */
  admin: [
    'Dashboard',
    'Customers',
    'Orders',
    'Projects',
    'Missions',
    'Deliveries',
    'Inventory',
    'Staff Management',
    'Invoices',
    'Payroll',
    'Reports',
    'Support',
    'Chauffeur',
    'Events',
    'Guest Requests',
    'Luxury Items',
    'Vendors',
    'Purchase Requests',
    'Quotes',
    'Purchase Orders',
    'Fleet',
    'Warehouses',
    'Staff Terminal',
    'Settings',
    'Security Protocol',
    'Leave & Absence',
  ],
  /** DB role: operation — normalized frontend: operations */
  operation: [
    'Dashboard',
    'Projects',
    'Orders',
    'Missions',
    'Deliveries',
    'Invoices',
    'Staff Terminal',
    'Leave & Absence',
    'Pay & Records',
  ],
  procurement: [
    'Dashboard',
    'Purchase Requests',
    'Vendors',
    'Quotes',
    'Purchase Orders',
    'Invoices',
    'Audit Log',
    'Leave & Absence',
    'Pay & Records',
  ],
  logistics: [
    'Dashboard',
    'Missions',
    'Deliveries',
    'Fleet',
    'Routes',
    'Tracking',
    'Urgent Tasks',
    'Staff Terminal',
    'Leave & Absence',
    'Pay & Records',
  ],
  inventory: [
    'Dashboard',
    'Inventory',
    'Warehouses',
    'Inventory Alerts',
    'Audit Log',
    'Staff Terminal',
    'Leave & Absence',
    'Pay & Records',
  ],
  concierge: [
    'Dashboard',
    'Orders',
    'Events',
    'Guest Requests',
    'Luxury Items',
    'Inventory',
    'VIP Access',
    'Chauffeur',
    'Leave & Absence',
    'Pay & Records',
  ],
  /** DB role: staff — field staff; effective permissions = staff ∩ company admin (see login API) */
  staff: [
    'Dashboard',
    'Staff Terminal',
    'Leave & Absence',
    'Pay & Records',
  ],
  customer: [
    'Dashboard',
    'Marketplace',
    'My Orders',
    'Invoices',
    'Track Delivery',
    'Purchase Requests',
    'Chauffeur',
    'Concierge Events',
    'Guest Requests',
  ],
};
